"""Regions and individuals as this lab names them, pinned to real series.

Every name below is an actual series read out of a .lif on the L drive or the
scope computer.

THREE DEFECTS ARE PINNED HERE, all found against real data.

FIRST, THE WRONG LEVEL. The first survey read FILENAMES and found `head` 17
times in 1,793 of them, concluding region labels were rare. One Leica file
holds many stacks and the student names the region ON THE STACK: across the
8,446 series inside those files, head appears 235 times, tail 259, mid 177.

SECOND, THE UNDERSCORE. `_` is a word character, so `\\bmid\\b` cannot match
inside `full worm 1_mid`. That alone reported 0 animals with all three
regions while `full worm 1_head`, `full worm 1_mid` and `full worm 1_tail`
sat in the output being read.

THIRD, `back` IS NOT A TAIL. It appears 72 times beside ventral (229), top
(108) and bottom (125) - these say which side of the animal or which end of
the stack. Mapping it to tail would have mislabelled 72 stacks as posterior.
"""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT / "tools" / "drive_audit")]

import lab_regions as lr   # noqa: E402

results = []


def check(name, condition, detail=""):
    results.append((name, bool(condition), detail))
    print(f"  {'PASS' if condition else 'FAIL'}  {name}"
          + (f"  [{detail}]" if detail else ""))


print("\n--- underscores separate, whatever the regex engine thinks ------")

check("full worm 1_mid is a midbody",
      lr.region_of("full worm 1_mid") == "midbody",
      "the \\b in \\bmid\\b cannot fire against `1_mid` unsplit")
check("full worm 1_head is a head",
      lr.region_of("full worm 1_head") == "head")
check("full worm 2_tail is a tail",
      lr.region_of("full worm 2_tail") == "tail")
check("dots separate too", lr.region_of("worm3.head") == "head")

print("\n--- regions, as actually written -------------------------------")

for name, expect in (("head", "head"), ("anterior", "head"),
                     ("pharynx", "head"), ("midbody", "midbody"),
                     ("mid", "midbody"), ("vulva", "midbody"),
                     ("tail", "tail"), ("posterior", "tail")):
    check(f"{name!r} -> {expect}", lr.region_of(f"worm 1 {name}") == expect)

check("a name stating TWO regions states neither",
      lr.region_of("head+mid") == "",
      "head+mid spans both; picking one would be a guess")
check("a plain autogenerated name has no region",
      lr.region_of("Series012") == "")

print("\n--- orientation is not anatomy ---------------------------------")

check("`back` is NOT a tail",
      lr.region_of("full worm 1_back") == "",
      "72 series would have been mislabelled posterior")
check("...it is read as dorsal",
      lr.orientation_of("full worm 1_back") == "dorsal")
check("`ventral` is orientation, not a region",
      lr.region_of("worm 2 ventral") == ""
      and lr.orientation_of("worm 2 ventral") == "ventral")
check("`top` and `bottom` are stack ends",
      lr.orientation_of("worm 2 top") == "stack top"
      and lr.orientation_of("worm 2 bottom") == "stack bottom")

print("\n--- the individual is what ties three tiles together -----------")

check("full worm 3_head belongs to animal 3",
      lr.animal_of("full worm 3_head") == "3")
check("w7 tail belongs to animal 7", lr.animal_of("w7 tail") == "7")
check("worm 12 mid belongs to animal 12",
      lr.animal_of("worm 12 mid") == "12")
check("a series with no animal number yields none",
      lr.animal_of("Series004") == "")

# THE POOL THAT MATTERS: three tiles, one animal.
series = [{"series_name": f"full worm {n}_{region}"}
          for n in (1, 2) for region in ("head", "mid", "tail")]
series.append({"series_name": "full worm 3_head"})
animals = lr.group_by_animal(series, lambda item: "one.lif")
check("two animals complete, one partial, from six plus one series",
      lr.completeness(animals) == {3: 2, 2: 0, 1: 1},
      f"{lr.completeness(animals)}")

# DEDUPLICATION. 10720_N2_IBD5.lif is held on L twice and on the scope once;
# keying on the full path counted its 9 animals three times and turned 31
# complete animals into 54.
copies = []
for share in ("L:\\a", "L:\\backup", "\\\\SCOPE\\x"):
    for region in ("head", "mid", "tail"):
        copies.append({"series_name": f"full worm 1_{region}",
                       "path": f"{share}\\10720_N2_IBD5.lif"})
by_path = lr.group_by_animal(copies, lambda i: i["path"])
by_name = lr.group_by_animal(copies, lambda i: i["path"].split("\\")[-1])
check("keying on the full path counts one animal three times",
      len(by_path) == 3)
check("...and keying on the filename counts it once",
      len(by_name) == 1,
      "the same file on three shares is one animal, not three")

print()
failed = [n for n, ok, _ in results if not ok]
print(f"{len(results) - len(failed)} of {len(results)} checks passed")
if failed:
    for name in failed:
        print(f"   FAILED: {name}")
    raise SystemExit(1)
print("LAB_REGIONS_PASS")
